version: "3.9"
services:
  db:
    image: postgres
    env_file: 
      - ./.env
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
  backend:
    build: backend/.
    env_file: 
      - ./.env
    environment:
      - DB_PORT=5432
      - DB_HOST=db
      - MAIL_SMTP=smtp.gmail.com
      - NODE_ENV=production
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
  frontend:
    build: frontend/.
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - backend      
  loadbalancer:
    image: nginx
    environment:
      - NGINX_DOMAIN=accamargo.ddns.net
    ports:
      - 443:443
      - 80:80
    volumes: 
      - ./nginx:/etc/nginx
    command: /bin/bash -c "sh /etc/nginx/run_nginx.sh"
    depends_on:
      - backend
